# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Septian Razi
email: raziseptian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! Feel free to look at all the stuff I've done on this website. 
  You can also find my more traditional CV on the top menu.

  - Razi
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://septianrazi.github.io" # the base hostname & protocol for your site
twitter_username: septianrazi
github_username: septianrazi
image: /assets/images/og-hero.png

markdown: kramdown
highlighter: rouge

author:
  name: Septian Razi
  twitter: septianrazi

social:
  name: Septian Razi
  links:
    - https://linkedin.com/in/septianrazi/
    - https://github.com/septianrazi/

# Analytics
google_analytics: G-Y1CJPZZ5QY

# Build settings
# theme: minima
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - index2.html
  - index_3.html
  - migrate_collections.rb

collections_dir: collections

collections:
  work:
  projects:
  blog:
    output: true
    permalink: /blog/:title/
